-- This is only for documentation, the actual changes are made by the installer
-- scripts.
--
--
-- Update TURNS host and port
--
-- { type = "turns", host = "turn.nordeck.corp", port = 443, transport = "tcp", secret = true, ttl = 86400, algorithm = "turn" }
--
--
-- Enable https_ports with an empty list to prevent the service warning
--
-- https_ports = { };
