-- this is only for documentation, the actual changes are made by the installer
-- scripts.
--
-- Rate limits for incoming connections:
--
-- limits = {
--   c2s = {
--     rate = "1024kb/s";
--   };
--   s2sin = {
--     rate = "1024kb/s";
--   };
-- }
